const USER_SIGNED_UP = "USER_SIGNED_UP";

const USER_SIGNED_OUT = "USER_SIGNED_OUT";

const SET_PIZZA_TOPPINGS = "SET_PIZZA_TOPPINGS";

const SET_PIZZA_BASE = "SET_PIZZA_BASE";

const SET_MODAL_OPEN = "SET_MODAL_OPEN";

const SET_MODAL_CLOSE = "SET_MODAL_CLOSE";

export {
  USER_SIGNED_UP,
  USER_SIGNED_OUT,
  SET_PIZZA_TOPPINGS,
  SET_PIZZA_BASE,
  SET_MODAL_OPEN,
  SET_MODAL_CLOSE,
};
